# Generated by Django 2.2.4 on 2019-08-25 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StaticMediaPages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carosoul',
            name='image',
            field=models.ImageField(default='1.0', upload_to='carousel/'),
        ),
        migrations.AddField(
            model_name='carosoul',
            name='publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='carosoul',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='carosoul',
            name='short_description',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='carosoul',
            name='subtitle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='carosoul',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
