# Generated by Django 2.2.4 on 2019-08-25 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StaticMediaPages', '0003_auto_20190825_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='designation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='image',
            field=models.ImageField(default='https://mdbootstrap.com/img/Photos/Avatars/img%20(30).jpg', upload_to='testimonial/'),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='testimonial',
            field=models.TextField(default='', max_length=250),
        ),
    ]
