# Generated by Django 2.2.4 on 2019-08-25 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StaticMediaPages', '0004_auto_20190825_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='image',
            field=models.ImageField(default='https://via.placeholder.com/150C', upload_to='company/'),
        ),
        migrations.AddField(
            model_name='companies',
            name='publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
